apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sf.fullname" . }}-master-pv
  labels:
  {{- include "sf.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/andrei/work/k8s-lab/local1/_data/redis-master
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath