# the application service
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  type: NodePort
  selector:
    app: guestbook
  ports:
  - port: 3000       # this is the port exposed by the service
    protocol: TCP
    targetPort: 3000 # this is the port your app listens to
    nodePort: 30000  # this is the port exposed externally by the service