apiVersion: v1
kind: Service
metadata:
  name: emqx-headless
  namespace: emqx-5
spec:
  ports:
    - port: 1883
      name: mqtt
    - port: 18083
      name: dashboard
  clusterIP: None  # This makes the service "headless"
  selector:
    app: emqx