###################################
#         EMQX Deployment         #
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:latest
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 18083
          name: dashboard
        resources:
          requests:
            memory: "1024Mi"  # 1024Mi = 1GB
            cpu: "2000m"      # 2000m = 2 cores
          limits:
            memory: "2048Mi"  # 2048Mi = 2GB
            cpu: "3000m"      # 3000m = 3 cores

---
apiVersion: v1
kind: Service
metadata:
  name: emqx-service
spec:
  type: NodePort
  selector:
    app: emqx
  ports:
  - protocol: TCP
    port: 1883
    targetPort: 1883
    nodePort: 31883  # Optional: Kubernetes chooses a port if not specified
---

###################################
#          App Deployment         #
###################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-cluster-reader
  labels:
    app: in-cluster-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: in-cluster-reader
  template:
    metadata:
      labels:
        app: in-cluster-reader
    spec:
      containers:
      - name: in-cluster-reader
        image: aidamian/basic_mqtt_listener
        resources:
          requests:
            memory: "256Mi"   # 256Mi = 0.25GB
            cpu: "500m"       # 500m = 0.5 cores
          limits:
            memory: "1024Mi"  # 1024Mi = 1GB
            cpu: "2000m"      # 2000m = 2 cores
