apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-test-nodejs
spec:
  replicas: 4
  selector:
    matchLabels:
      run: basic-test-nodejs
  template:
    metadata:
      labels:
        run: basic-test-nodejs
    spec:
      containers:
      - name: test-nodejs-container
        image: aidamian/simple-test-nodejs        
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: basic-test-nodejs-svc
spec:
  type: NodePort
  selector:
    run: basic-test-nodejs
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080  # Optional: Remove or change this if you want Kubernetes to assign a port automatically
