FROM aidamian/base_llm_env:latest
WORKDIR /test_app

RUN pip install psycopg2-binary

# basic stuff
ADD src/mixins ./mixins/
ADD src/app_utils.py ./app_utils.py
ADD src/version.py ./version.py

# specific app stuff
ADD src/monitor ./monitor/
ADD src/main_monitor.py ./main.py

ENV PORT=5050
EXPOSE $PORT
# ENV PYTHONPATH="/test_app"
CMD uvicorn main:app --host 0.0.0.0 --port $PORT
