FROM aidamian/base_th_llm_fastapi:latest
WORKDIR /test_app

# basic stuff
ADD src/mixins ./mixins/
ADD src/app_utils.py ./app_utils.py
ADD src/version.py ./version.py

# specific app stuff
ADD src/serving/ ./serving/
ADD src/main_serving.py ./main.py

ENV PORT=5050
EXPOSE $PORT
# ENV PYTHONPATH="/test_app"
CMD uvicorn main:app --host 0.0.0.0 --port $PORT
