apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-test-one.fullname" . }}-guestbook
  labels:
    app: guestbook
  {{- include "helm-test-one.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.guestbook.replicas }}
  selector:
    matchLabels:
      app: guestbook
    {{- include "helm-test-one.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: guestbook
      {{- include "helm-test-one.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.guestbook.guestbook.image.repository }}:{{ .Values.guestbook.guestbook.image.tag
          | default .Chart.AppVersion }}
        name: guestbook
        ports:
        - containerPort: 3000
          name: http
        resources: {{- toYaml .Values.guestbook.guestbook.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-test-one.fullname" . }}-guestbook
  labels:
    app: guestbook
  {{- include "helm-test-one.labels" . | nindent 4 }}
spec:
  type: {{ .Values.guestbook.type }}
  selector:
    app: guestbook
  {{- include "helm-test-one.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.guestbook.ports | toYaml | nindent 2 -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-test-one.fullname" . }}-master
  labels:
    app: redis
    role: master
  {{- include "helm-test-one.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app: redis
      role: master
    {{- include "helm-test-one.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: redis
        role: master
      {{- include "helm-test-one.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.master.redisMaster.image.repository }}:{{ .Values.master.redisMaster.image.tag
          | default .Chart.AppVersion }}
        name: redis-master
        ports:
        - containerPort: 6379
          name: redis-server
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-storage
      volumes:
      - emptyDir: {}
        name: redis-storage
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-test-one.fullname" . }}-master
  labels:
    app: redis
    role: master
  {{- include "helm-test-one.labels" . | nindent 4 }}
spec:
  type: {{ .Values.master.type }}
  selector:
    app: redis
    role: master
  {{- include "helm-test-one.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.master.ports | toYaml | nindent 2 -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-test-one.fullname" . }}-slave
  labels:
    app: redis
    role: slave
  {{- include "helm-test-one.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.slave.replicas }}
  selector:
    matchLabels:
      app: redis
      role: slave
    {{- include "helm-test-one.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: redis
        role: slave
      {{- include "helm-test-one.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args: {{- toYaml .Values.slave.redisSlave.args | nindent 8 }}
        command:
        - /bin/sh
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.slave.redisSlave.image.repository }}:{{ .Values.slave.redisSlave.image.tag
          | default .Chart.AppVersion }}
        name: redis-slave
        ports:
        - containerPort: 6379
          name: redis-server
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-storage
      volumes:
      - emptyDir: {}
        name: redis-storage
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-test-one.fullname" . }}-slave
  labels:
    app: redis
    role: slave
  {{- include "helm-test-one.labels" . | nindent 4 }}
spec:
  type: {{ .Values.slave.type }}
  selector:
    app: redis
    role: slave
  {{- include "helm-test-one.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.slave.ports | toYaml | nindent 2 -}}