#########################
###       App         ###
#########################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-test-py
  namespace: basic-clusters
  labels: # this is not mandatory but it is a good practice
    run: basic-test-py
spec:
  replicas: 4
  selector:
    matchLabels:
      run: basic-test-py
  template:
    metadata:
      labels:
        run: basic-test-py
    spec:
      containers:
      - name: test-py-container
        image: aidamian/basic_test_fastapi        
        ports:
        - containerPort: 5050
          protocol: TCP
        # enviroment variables
        env:
        - name: PORT
          value: "5050"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: basic-test-app-secrets
              key: redis-password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: basic-test-app-secrets
              key: postgres-password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: basic-test-app-secrets
              key: postgres-user
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: basic-test-app-secrets
              key: postgres-db
---
apiVersion: v1
kind: Service
metadata:
  name: basic-test-py-svc
  namespace: basic-clusters
spec:
  type: ClusterIP
  selector:
    run: basic-test-py
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050      
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-test-py-ingress
  namespace: basic-clusters
  annotations:
    # next part is a bit tricky, but it works
    # if rewrite-target is used simply with / then
    # the path no matter how long will be rewritten to /
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2 
spec:
  rules:
  - http:
      paths:
      - path: /cluster_test(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: basic-test-py-svc
            port:
              number: 5050
---


#########################
###       Redis       ###
#########################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: basic-clusters
  labels: # this is not mandatory but it is a good practice
    app: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
      - name: redis-master-container
        image: redis:alpine
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: basic-test-app-secrets
              key: redis-password
        command: ["/bin/sh"]
        args: ["-c","redis-server --loglevel debug --requirepass $(REDIS_PASSWORD)"]              
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        emptyDir: {}        
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: basic-clusters
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-master
---
# the Redis slave deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: basic-clusters
  labels:
    app: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
      - name: redis-slave-container
        image: redis:alpine
        command: ["/bin/sh"]
        # --slaveof redis-master 6379 # this must point to the name of the master _service_
        args: ["-c","redis-server --slaveof redis-master 6379 --loglevel debug"]
        ports:
        - name: redis-server
          containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        emptyDir: {}
---
# the Redis slave service
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: basic-clusters
  labels:
    app: redis-slave
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-slave
---



#########################
###       Postgres    ###
#########################

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgc-nfs-pv
  namespace: basic-clusters
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.56  
    path: "/srv/nfs/k8s/pg_storage/basic-test-py-clusters"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgc-nfs-pvc
  namespace: basic-clusters
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pgc-nfs-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: basic-clusters
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: basic-test-app-secrets
              key: postgres-password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: basic-test-app-secrets
              key: postgres-user
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: basic-test-app-secrets
              key: postgres-db
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: pgc-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: basic-clusters
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres