apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-test-py
  namespace: basic-ns12
  labels: # this is not mandatory but it is a good practice
    app: basic-test-py
spec:
  replicas: 4
  selector:
    matchLabels:
      run: basic-test-py
  template:
    metadata:
      labels:
        run: basic-test-py
    spec:
      containers:
      - name: test-py-container
        image: aidamian/simple_test_fastapi        
        ports:
        - containerPort: 5050
          protocol: TCP
        #enviroment variables
        env:
        - name: PORT
          value: "5050"
---
apiVersion: v1
kind: Service
metadata:
  name: basic-test-py-svc
  namespace: basic-ns12
spec:
  type: ClusterIP
  selector:
    run: basic-test-py
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-test-py-ingress
  namespace: basic-ns12
  annotations:
    # next part is a bit tricky, but it works
    # if rewrite-target is used simply with / then
    # the path no matter how long will be rewritten to /
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2 
spec:
  rules:
  - http:
      paths:
      - path: /simple_test(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: basic-test-py-svc
            port:
              number: 5050

