apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.56  # Înlocuiți cu IP-ul sau hostname-ul serverului NFS
    path: "/srv/nfs/k8s"
