apiVersion: v1
kind: Pod
metadata:
  name: read-test
spec:
  containers:
  - name: reader
    image: busybox
    command: ["/bin/sh", "-c"]
    args: 
    - |
      while true; do
        if [ -f /data/testfile.txt ]; then
          cat /data/testfile.txt
        else
          echo "Waiting for file..."
        fi
        sleep 5
      done
    volumeMounts:
    - name: nfs
      mountPath: "/data"
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs-pvc
