apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-application-2-app
  namespace: demo-nodejs-emqx
  labels:
    app: application-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-2
  template:
    metadata:
      labels:
        app: application-2
    spec:
      containers:
        - name: nodejs-application-2-app
          image: aixpand/demo-nodejs-emqx:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_TYPE
              value: "subscriber"
            - name: MQTT_HOST
              valueFrom:
                secretKeyRef:
                  name: demo-nodejs-emqx-secrets
                  key: mqtt_host
            - name: MQTT_PORT
              value: "1883"
            - name: PUBLISH_CADENCE
              value: "1"
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  name: demo-nodejs-emqx-secrets
                  key: mqtt_user
            - name: MQTT_PASS
              valueFrom:
                secretKeyRef:
                  name: demo-nodejs-emqx-secrets
                  key: mqtt_pass
            - name: MINIO_ENDPOINT
              value: "minio-service.demo-nodejs-emqx.svc.cluster.local"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_USE_SSL
              value: "false"
            - name: MINIO_BUCKET
              value: "demo-nodejs-emqx"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-nodejs-emqx-secrets
                  key: minio_access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-nodejs-emqx-secrets
                  key: minio_secret_key