---
#configs for pg
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-ai-app-config
  namespace: hwal
data:
  postgres-db: postgresdb
  postgres-user: pguser
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru  