#pv for Postgres
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-nfs
  namespace: demo-ai-app-ns
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: "/srv/nfs/k8s"
    server: 192.168.1.56
    readOnly: false
---
#pvc for Postgres
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  namespace: demo-ai-app-ns
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: pg-pv-nfs
---
# pg deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: demo-ai-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-ai-app-secrets
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: demo-ai-app-config
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: demo-ai-app-config
              key: postgres-user
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          subPath: pg
          readOnly: false
          name: pg-volume
      volumes:
      - name: pg-volume
        persistentVolumeClaim:
          claimName: pg-pvc
---
#pg service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: demo-ai-app-ns
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres