apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ai-app-monitor
  namespace: hwal
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-ai-app-monitor
  template:
    metadata:
      labels:
        run: demo-ai-app-monitor
    spec:
      containers:
      - name: demo-ai-app-monitor-container
        image: aidamian/basic_cluster_monitor_test 
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 4041
          protocol: TCP
        #enviroment variables
        env:
        - name: PORT
          value: "4041"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-ai-app-secrets
              key: redis-password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-ai-app-secrets
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: demo-ai-app-config
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: demo-ai-app-config
              key: postgres-user
---
apiVersion: v1
kind: Service
metadata:
  name: demo-ai-app-monitor-svc
  namespace: hwal
spec:
  type: ClusterIP
  selector:
    run: demo-ai-app-monitor
  ports:
    - protocol: TCP
      port: 4041
      targetPort: 4041
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ai-app-monitor-ingress
  namespace: hwal
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /ai_test_monitor(/|$)(.*) # 172..../ai_test_monitor/health
        pathType: Prefix
        backend:
          service:
            name: demo-ai-app-monitor-svc
            port:
              number: 4041