#pv for serving app
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-app-serve-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: "/nfs/k8s/ai_app_storage"
    server: 172.31.255.148
    readOnly: false
---
#pv for Postgres
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-app-pg-pv
  namespace: hwal
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: "/nfs/k8s/pg_storage/ai_app_storage"
    server: 172.31.255.148
    readOnly: false