apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqx-account
  namespace: emqx-v1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: emqx-role
  namespace: emqx-v1
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: emqx-role-binding
  namespace: emqx-v1
subjects:
  - kind: ServiceAccount
    name: emqx-account
    namespace: default
roleRef:
  kind: Role
  name: emqx-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emqx-nfs-pv
  namespace: emqx-v1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.56
    path: "/srv/nfs/k8s/emqx_storage"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-nfs-pvc
  namespace: emqx-v1
spec:
    accessModes:
        - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    volumeName: emqx-nfs-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: emqx-v1
spec:
  serviceName: "emqx-headless"
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      serviceAccountName: emqx-account
      containers:
        - name: emqx
          image: emqx/emqx:5.0
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 18083
              name: dashboard
          env:
            - name: EMQX_NAME
              value: emqx
            - name: EMQX_CLUSTER__DISCOVERY
              value: k8s
            - name: EMQX_CLUSTER__K8S__APISERVER
              value: "https://kubernetes.default.svc:443"
            - name: EMQX_CLUSTER__K8S__SERVICE_NAME
              value: emqx-headless
            - name: EMQX_CLUSTER__K8S__NAMESPACE
              value: default
            - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
              value: ip
            - name: EMQX_CLUSTER__K8S__APP_NAME
              value: emqx