apiVersion: v1
kind: PersistentVolume
metadata:
  name: emqx-nfs-pv
  namespace: emqx-v1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.56
    path: "/srv/nfs/k8s/emqx_storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-nfs-pvc
  namespace: emqx-v1
spec:
    accessModes:
        - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    volumeName: emqx-nfs-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: emqx-v1
spec:
  serviceName: "emqx-headless"
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      serviceAccountName: emqx-account
      initContainers:
      - name: init-emqx-node-name
        image: busybox
        command: ['sh', '-c', 'echo -n "export EMQX_NODE__NAME=emqx@$POD_IP; echo \"var: $EMQX_NODE__NAME\"" > /app-config/emqx-env.sh && chmod +x /app-config/emqx-env.sh']
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: emqx-node-name
          mountPath: /app-config
      containers:
      - name: emqx
        image: emqx/emqx:5.0.0
        command: ["/bin/sh", "-c", "cat /app-config/emqx-env.sh && /app-config/emqx-env.sh && emqx foreground"]
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 18083
          name: dashboard
        env:
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__APISERVER
          value: "https://kubernetes.default.svc.cluster.local:443"
          # value: "https://kubernetes.default.svc:443"
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: emqx-headless
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: emqx-v1
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          value: ip

        volumeMounts:
        - name: emqx-node-name
          mountPath: /app-config
      volumes:
      - name: emqx-node-name
        emptyDir: {}                 

---
apiVersion: v1
kind: Service
metadata:
  name: emqx-headless
  labels:
    app: emqx
  namespace: emqx-v1
spec:
  ports:
  - port: 4369  # For EPMD (Erlang Port Mapper Daemon)
    name: epmd
  - port: 18083  # For EMQX Dashboard
    name: dashboard
  clusterIP: None
  selector:
    app: emqx
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-external
  namespace: emqx-v1
spec:
  type: NodePort  # Use LoadBalancer if in cloud environment that supports it
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
  - port: 18083
    targetPort: 18083
    name: dashboard
  selector:
    app: emqx
