apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: basic-ns11
type: Opaque
data:
  redis-password: # add here base64 password
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: basic-ns12
type: Opaque
data:
  redis-password: # add here base64 password
