apiVersion: v1
kind: Secret
metadata:
  name: basic-test-app-secrets
  namespace: basic-ns11
type: Opaque
data:
  redis-password: # add here base64 password
  another-password: # add here base64 password
  yet-another-secret: # add here base64 secret
  maybe-some-secret-user: # add here base64 secret
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-test-app-secrets
  namespace: basic-ns12
type: Opaque
data:
  redis-password: # add here base64 password
