name: Test kmonitor container working within a cluster

on: 
  push:
    paths:
      - 'labs/py/**'  # Specify path to your directory

jobs:
  build-and-push-k8s-pytest-image:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and Push
        run: |
          cd labs/py/
          chmod +x build.sh  # Ensure the script is executable
          ./build.sh        